- .github/workflows/build.yml
Add python 3.8 binary wheels for mac and linux - needed for chia-blockchain ci with upgraded install methods
> Pyhton38 wheels

- .github/workflows/build-aarch64.yml
- .github/workflows/build.yml
- .gitignore
- src/1weso_test.cpp
- src/2weso_test.cpp
- src/alloc.hpp
- src/avx512_test.cpp
- src/prover_test.cpp
- src/python_bindings/fastvdf.cpp
- src/threading.h
- src/vdf_bench.cpp
- src/vdf_client.cpp
the way things work right now, `init_gmp()` has to be called very early, before any `integer` object is created (really, before any GMP integer is initialized).
The consequence of not doing this is that an integer may be allocated by the default allocator, and freed by our custom allocator. i.e. memory corruption.
> fix use of custom allocator for GMP

- src/integer_common.h
- src/proof_common.h
- src/provers.h
there was a misunderstanding of `mpz_export()` causing 0 (which yields an empty vector) to trigger out-of-bounds accesses in code that assumed the vector had at least 1 element.
> fix out-of-bound accesses

- src/callback.h
- src/threading.h
- src/vdf.h
- src/vdf_fast.h
This makes the tests (`./prover_test`, `./1weso_test` and `./2weso_test`) pass the thread sanitizer.
The CI should run these with address-sanitizer and thread sanitizer, but the build scripts should probably be unified first.
> fix data races

- src/Reducer.h
this fixes issues highlighted by undefined-sanitizer:
```
Reducer.h:84:42: runtime error: left shift of negative value -1
Reducer.h:209:23: runtime error: left shift of negative value -218085997599378178
Reducer.h:86:42: runtime error: left shift of negative value -1
```
Someone that knows what's supposed to happen should look at this. I assume that the intention was to have the unsigned shifting behavior. I was a bit tempted to change thes `<< 1` to `* 2`, since that has the same semantics but with a wider contract (notably allows negative numbers). However, given that one of those numbers seems to have a lot of bits in it, using `*` might cause *overflow* instead.
> fix undefined behavior in left-shifting negative numbers

- src/integer_common.h
This increases performance of hashing to prime when generating the
discriminant by about 2x.
> Use only Baillie-PSW primality test when hashing to prime

- src/bqfc.c
- src/bqfc.h
- src/proof_common.h
- src/vdf_client.cpp
- src/verifier.h
- tests/test_verifier.py
The size is the same regardless of discriminant bits or a form being
'special' (identity or generator). This allows using a fixed-size object
(bytes100) for quadratic forms in chia-blockchain.
> Require size of serialized compressed forms to be 100 bytes

- src/prover_slow.h
this fixes a division by zero in the tests (because `k` = 0) and this expression:
```
ceil(1.0 * num_iterations / (k * l))
```
Invokes UB. On ARM, this would manifest as the loop not terminating (because the end condition was "infinite"), and it would then access an uninitialized `form` object from the end of `intermediates`
> fix case where k=0, which happens in tests

- src/Reducer.h
lzcnt64 doesn't have lzcnt64_hard implementation resulting in no lzcnt64_hard symbol being created, failing at linking.
You should be using generic lzcnt64() symbol which gets implemented as hard or soft, depending on whether hard implementation is available.
> do not use lzcnt64_hard directly to allow compilation on ppc64le

- src/util.h
This fixes a compile issue on OpenBSD, because bswap is not supported. Tested on OpenBSD 6.8 stable.
Furthermore, the man pages of [NetBSD](http://man.netbsd.org/bswap.3) and [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=bswap64&apropos=0&sektion=0&manpath=FreeBSD+12.2-RELEASE+and+Ports&arch=default&format=html) indicate these platforms do support bswap{16,32,64}.
Same as https://github.com/Chia-Network/chiapos/pull/183.
> use swap{16,32,64} from <endian.h> on OpenBSD

- .github/workflows/test.yaml
- src/2weso_test.cpp
- src/prover_test.cpp
- src/python_bindings/fastvdf.cpp
- src/verifier.h
- src/verifier_test.cpp
- tests/test_n_weso_verifier.py
Compress y form from 100 bytes to 33 bytes and adds python bindings for compression/verification. Note that this modifies chiavdf n-wesolowski verification as well, by factoring out the common parts in the verifiers.
> Compress y.

- src/vdf.h
Add missing logic to handle stopped signal in one-weso proofs.
For one-weso proofs, vdf_client launches two threads to do its work. One
repeatedly squares until a given number of iterations, the second waits
until the first is done squaring and then computes a proof.
The squaring-thread properly handles the "stopped" signal and aborts
early, if signaled. That way, it never reaches the targeted iterations.
The 1weso-thread waits until the target iterations are reached, but does
not handle the "stopped" signal. Thus, for stopped iters, it waits
infinitely.
This situation regularly occurs, vdf_client is running for a bluebox
timelord. Whenever the timelord (Python) process restarts, network
communication errors out, killing the squaring thread. But instead of
the while vdf_client exiting …
> Fix deadlock in vdf_client

- pyproject.toml
- setup.py
This will stop testpypi uploads from failing in CI
> Correctly handle fallback_version

- .github/workflows/test.yaml
https://github.com/Chia-Network/chiavdf/actions/runs/3888384319/jobs/6635642471#step:3:16
```
E: Package 'libpython3.8-dev' has no installation candidate
```
I suspect that this broke with the transition of `ubuntu-latest` runners from Ubuntu 20.04 to 22.04.  Unless we need 3.8 specifically then let's just take whatever the Ubuntu is giving us, or explicitly matrix across 'all' versions.
Draft for:
> use libpython3-dev instead of libpython3.8-dev

- src/vdf_client.cpp
The user will not be able to start vdf_client when the error message is incorrect.
> Fix error message on invalid number of args for `vdf_client`.

- .github/workflows/build.yml
Use `macos-11` instead of `macos-latest` for proper GMP artifacts to include in the wheel
This creates a wheel that does work currently on macOS 10.14+ as it includes a version of the GMP library that runs on those platforms.
The version of GMP included when using `macos-latest` does not run on macOS 10.14
> Switch to macos-11 for building

- .github/workflows/build.yml
- pyproject.toml
Puts most `cibuildwheel` configuration into `pyproject.toml` instead of using envvars in the github actions.
The rationale is that this makes it a little bit easier to build the wheel locally for debugging and testing as there is less configuration specific to GH actions
Note some of the envvars refer to GH action matrix items, so those remain in the GH workflow.
> Move cibw config to pyproject.toml

- .github/workflows/build.yml
- setup.py
Remove python 3.7
Remove unused code in setup.py related to macos builds. This code was never actually executed.
> Remove python 3.7 and some cleanup

- src/CMakeLists.txt
Cmake is deprecating the way pybind finds the python interpreter. See https://cmake.org/cmake/help/latest/policy/CMP0148.html and pybind/pybind11#4719
> Update to pybind v2.11.1

- .github/workflows/build-riscv64.yml
- .github/workflows/build.yml
- pyproject.toml
- setup.py
For increased simplicity, this PR removes the Cmake version check from setup.py. The minimum cmake version is set in the CMakeLists.txt
Also removes distutils from setup.py
Switches out the CNI-specific windows `delocate` for `delvewheel` which is the current method recommended by `cibuildwheel` for wheel repair on Windows. Appears to work but might need some additional testing on other CPU flavours to make sure the correct DLL is loaded.
- Tested on a Haswell CPU and the proper DLL was loaded (mpir_haswell.dll) 
- Confirmed all the other DLLs are present in the wheel package, so I hope this is working correctly
> Add python 3.12

- .github/workflows/build-c-libraries.yml
On windows, need bash to make the syntax valid
For all, needed contents: write to be able to actually upload to the releases
> Fix uploads for releases of the c wrapper

- .github/workflows/test.yaml
The `macos-latest` tag was switched to Apple Silicon (arm) cpus, so use `macos-12` label to run the various tests on Intel CPU
> Change macos-latest to macos-12 for intel CPU

- src/vdf.h
This was discovered trying to figure out why #174 keeps failing the TSAN test.
Per the documentation, I don't think this should be required, but this has minimimal overall impact and makes sure the output won't be interleaved or cause TSAN issues
> Add some locking about stdout to avoid some false positives in TSAN

- src/c_bindings/c_wrapper.h
Go lint/vet tools (where I primary use these bindings) have gotten better and started complaining about this missing include
seems to only matter for versions older than c99, but doesn't hurt newer versions
> Include stdbool.h in the c_wrapper/bindings. 

- src/callback.h
- src/provers.h
- src/python_bindings/fastvdf.cpp
From xearl4:
The "fast" 1-Wesolowski prover inadvertently mixed up parameters in the call to ApproximateParameter.
ApproximateParameter's signature has L followed by K:
void ApproximateParameters(uint64_t T, uint32_t& L, uint32_t& K)
However, the 1-Weso calls used K followed by L:
ApproximateParameters(num_iterations, k, l);
While this typo does not affect the correctness of the created 1-Weso proof, this causes 1-Weso proving to be _much_ slower than necessary. In isolated testing, the 1-Weso proof generation is up to 10x slower.
Funnily enough, the "slow" VDF impl (in `src/provers_slow.h`) uses a separate 1-Weso prover implementation which _doesn't_ suffer from this bug, thus making the "slow" VDF impl faster than the "fast" overall.
To be clear: the fixed bug _only_ affects the …
> xearl4's ApproximateParameter fix and GIL related parameter copies

- src/CMakeLists.txt
`chiavdf` may not have the same problem as `chiapos` - but this change seems like a good preventative measure just in case there is some future code that might cause issues
see `chiapos` PR https://github.com/Chia-Network/chiapos/pull/449
https://github.com/Chia-Network/chiapos/pull/449#issue-2517676917
> Add _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR when building wheel on windows

- src/proof_common.h
- src/vdf.h
- src/vdf_client.cpp
- src/vdf_fast.h
An assortment of cosmetic changes I have lying around. Might as well try to upstream them :)
> Misc cosmetic changes

- rust_bindings/build.rs
- src/CMakeLists.txt
Using a "fake" generator for the directory makes the directory work in a simplified cross platform way. 
> Multi-configuration generators ([Visual Studio], [Xcode], [Ninja Multi-Config]) append a per-configuration subdirectory to the specified directory unless a generator expression is used
> Use generator for output directory

- .github/workflows/hw-build.yml
j2cli (which itself was a fork of jinja2-cli) was abandoned by the maintainers when python deprecated the imp package. jinjanator continued the cycle by forking j2cli and removing all the code that relied in imp so it works up to python 3.13
> Remove j2cli for jinjanator for jinja template rendering

- src/CMakeLists.txt
Per recommendation from Arvid, debug builds are useful with `-Og` as this allows some optimizations but only those that don't interfere with debugging. (Note Cmake will add in `-g` for us already)
> Use Og for debug compiling

- .github/workflows/hw-build.yml
To support older versions of glibc, and because ubuntu-latest recently began defaulting to 24.04.
> Pin chiavdf-hw build workflow to ubuntu-22.04

- src/Makefile.vdf-client
The latest version of boost has removed the boost_system library from its distribution, as it is no longer
necessary.
> remove boost_system
